name: SuperAnnouncer
version: 3.0.3
main: me.Stefan923.SuperAnnouncer.SuperAnnouncer
description: Announce your news and tips.
softdepend: [PlaceholderAPI, SuperCore]
authors: [Stefan923]

commands:
  superannouncer:
    description: Infos about this plugin.
    aliases: [announcer, sannouncer]

permissions:
  superannouncer.admin:
    description: Acces to powerfull commands, like /announcer reload.
    default: op
  superannouncer.updatechecker:
    description: Shows a message when an update is available.
    default: op