name: SuperAnnouncer
version: 3.0.0
main: me.Stefan923.SuperAnnouncer.SuperAnnouncer
description: Announce your news and tips.
softdepend: [PlaceholderAPI, SuperCore]
authors: [Stefan923]

commands:
  superannouncer:
    description: Infos about this plugin.
    aliases: [announcer, sannouncer]

permissions:
  superannouncer.admin:
    description: Acces to powerfull commands, like /core reload.
    default: op